docs_dir: content
site_name: mopipe documentation
nav:
- API Documentation: api.md
- mopipe: index.md
theme:
  name: material
  features:
  - navigation.indexes
  - navigation.instant
  - navigation.sections
  - navigation.tracking
  - navigation.top
  - toc.follow
plugins:
- autorefs
markdown_extensions:
- admonition
- callouts
- markdown.extensions.extra
- meta
- pymdownx.betterem
- pymdownx.caret
- pymdownx.details
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tabbed: { alternate_style: true }
- pymdownx.tasklist: { custom_checkbox: true }
- pymdownx.tilde